// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/fc595bd854e0f619b538277f165e7537aa44255e/app-root-path/app-root-path.d.ts
declare module 'app-root-path' {
    interface RootPath {
        
        /**
         * Application root directory absolute path
         * @type {string}
         */
        path: string;

        /**
         * Resolves relative path from root to absolute path
         * @param {string} pathToModule
         * @returns {string}
         */
        resolve(pathToModule: string): string;

        /**
         * Resolve module by relative addressing from root
         * @param {string} pathToModule
         * @returns {*}
         */
        require(pathToModule: string): any;

        /**
         * Explicitly set root path
         * @param {string} explicitlySetPath
         */
        setPath(explicitlySetPath: string): void;

        toString(): string;
    }
    var RootPath: RootPath;
    export = RootPath;
}
